---
- name: Homebrew required taps
  homebrew_tap: tap={{ item }} state=present
  with_items:
    - homebrew/dupes
    - homebrew/apache
  tags:
    - httpd
    - brew


- name: Install Apache HTTPD
  homebrew: name=homebrew/apache/httpd22 state=present install_options=with-brewed-openssl
  tags:
    - httpd
    - brew

- name: Update httpd conf
  template: src=httpd.conf.j2 dest=/usr/local/etc/apache2/2.2/httpd.conf

- name: Add OpenCHS httpd conf
  template: src=openchs-config.conf.j2 dest=/usr/local/etc/apache2/2.2/extra/openchs-config.conf