version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

      - image: circleci/postgres:9.6
        environment:
        - POSTGRES_USER: openchs
        - POSTGRES_DB: openchs_test
        - POSTGRES_PASSWORD: password

    working_directory: ~/openchs-server

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.gradle" }}-{{ checksum "openchs-server-api/build.gradle" }}-{{ checksum "openchs-health-module-adapter/build.gradle" }}-{{ checksum "openchs-excel-import/build.gradle" }}
          - v1-dependencies-

      - run: sudo apt-get install make
      
      - run: make test_server

      - save_cache:
          paths:
            - ~/.m2
            - ~/.gradle
            - ~/openchs-server/.gradle
          key: v1-dependencies--{{ checksum "build.gradle" }}-{{ checksum "openchs-server-api/build.gradle" }}-{{ checksum "openchs-health-module-adapter/build.gradle" }}-{{ checksum "openchs-health-module-adapter/openchs-excel-import" }}