version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

      - image: circleci/postgres:9.6
        environment:
        - POSTGRES_USER: openchs
        - POSTGRES_DB: openchs_test
        - POSTGRES_PASSWORD: password

    working_directory: ~/openchs-server

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
    - checkout

    - restore_cache:
      keys:
      - v1-dependencies-{{ checksum "pom.xml" }}
      - v1-dependencies-

    - run: make test_server

    - save_cache:
      paths:
        - ~/.m2
      key: v1-dependencies-{{ checksum "pom.xml" }}